apiVersion: aquasecurity.github.io/v1beta1
kind: TraceePolicy
metadata:
    name: overview-policy
    annotations:
        description: sample overview policy
spec:
    scope:
      - container
    rules:
      - event: file_modified
      - event: open

