apiVersion: aquasecurity.github.io/v1beta1
kind: TraceePolicy
metadata:
  name: syscall--openat-events
  namespace: tracee-system
  annotations:
    description: traces open syscall events
spec:
  scope:
    - container
  rules:
    - event: open
      filters:
        - args.pathname=/usr/share/nginx/html*